Extension { #name : #UndefinedObject }

{ #category : #'*Dolphin to Pharo' }
UndefinedObject >> subclass: aSymbol instanceVariableNames: ivNames classVariableNames: cvNames poolDictionaries: pdNames classInstanceVariableNames: civNames [

	^ProtoObject subclass: aSymbol instanceVariableNames: ivNames classVariableNames: cvNames poolDictionaries: pdNames classInstanceVariableNames: civNames

]
